stages:
 
  - build
 
  - deploy
  

build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
     - export DOCKER_HOST=tcp://192.168.160.96:2375
     - export DOCKER_API_VERSION=1.39
     - docker info

     - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  stage: build # must match the stage name declared above
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  only:
     - master

deploy:
  stage: deploy # must match the stage name declared above
  image: alpine:3.8
  before_script:
    - apk add --no-cache git curl bash
    - curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
    - chmod u+x ./kustomize
    - mv kustomize /usr/local/bin/
    - mkdir kust
    - cd kust
    - git clone http://${CI_USERNAME}:${CI_PUSH_TOKEN}@192.168.160.174/aymen/appofapps.git
    - cd appofapps
    - git remote set-url origin http://${CI_USERNAME}:${CI_PUSH_TOKEN}@192.168.160.174/aymen/appofapps.git
    - git config --global user.name ${CI_USERNAME}
    - git config --global user.email ${CI_PUSH_TOKEN}
  script:
    
    - ls
    
    - git checkout master
    
    - git pull origin master --allow-unrelated-histories
    - cd dechetfrontend
    - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - cat kustomization.yaml
    - git commit -am '[skip ci] PROD image update'
    - git push origin master
  environment:
     name: production
  only:
     - master

